env:
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
#globals:
# plugins:
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always